### ISSUE TITLE
Missing: Form components are missing

### ISSUE THREAD

**Issue by thenishantgiri** [safak/next-dashboard-ui#15]
Only TeacherForm and StudentForm are available in the completed branch of this repository; please include other form components as well.

Thank You

**Comment by zpectrodev** [comment]
@thenishantgiri  The rest of the forms can be found in the following repo:

https://github.com/[safak/full-stack-school](https://github.com/safak/full-stack-school)

Regards

**Comment by thenishantgiri** [comment]
@ZpectroDigital Link redirects to a 404 page

Regards

**Comment by thenishantgiri** [comment]
@ZpectroDigital Thank You
